name: Generate Coverage Report

on: ["push", "pull_request"]

jobs:
    report:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls
              uses: coverallsapp/github-action@v1.1.0
              with:
                  github-token: ${{ secrets.github_token }}
