name: Generate Coverage Report

on: ["push", "pull_request"]

jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls
              uses: coverallsapp/github-action@v1.1.0
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: /home/runner/work/bizwhiz/bizwhiz/coverage/lcov.info
